spring:
  application:
    name: paymentservice
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:secret@mongodb:27017/payments?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

app:
  kafka:
    topic: ${KAFKA_TOPIC:payments}
